### ISSUE TITLE
Can't resolve 'react-dom/lib/EventPluginHub'

### ISSUE THREAD

**Issue by nickjuntilla** [stermedia/react-web-gifted-chat#3]
#### Issue Description

After trying the example with import { GiftedChat } from 'react-web-gifted-chat';

#### Steps to Reproduce / Code Snippets

Doing example

#### Expected Results

The example 

#### Additional Information

Got error: import { GiftedChat } from 'react-web-gifted-chat';

"react": "^16.0.0",
 "react-dom": "^16.0.0",

"react-web-gifted-chat": "0.0.4",

On web

**Comment by johniak** [comment]
Work in progress, I alread upgraded react version but its not fully functional, I will put it in the new release
